# Development specific overrides

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host('mailhog.localhost')"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
