FROM ocsinventory/ocsinventory-docker-image:2.10

# Étape 1: Mettre à jour les sources de paquets
RUN apt-get update

# Étape 2: Installer les outils de compilation et le gestionnaire de modules Perl 'cpanm'
# build-essential : contient les compilateurs (gcc, make...) nécessaires pour beaucoup de modules Perl
# cpanminus : contient l'utilitaire 'cpanm'
RUN apt-get install -y build-essential cpanminus


# Étape 3: Utiliser cpanm pour installer le module Perl requis
RUN cpanm XML::Entities

# Installer le module SOAP manquant
RUN apt-get update && \
    apt-get install -y libsoap-lite-perl && \
    rm -rf /var/lib/apt/lists/*

# Corriger le fichier de configuration
RUN sed -i 's/dbsrv/ocs-db/g' /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php