# Traefik Main Configuration
# Main Traefik configuration

# Entry Points
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# API and Dashboard
api:
  insecure: false
  dashboard: true

# Docker Provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

# Logging
log:
  level: INFO
  format: common
  filePath: /var/log/traefik/traefik.log

# Access Log
accessLog:
  format: common
  filePath: /var/log/traefik/access.log
