# Configuration statique de Traefik
# Ce fichier définit les points d'entrée, les providers et les certificats

global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Points d'entrée des requêtes (HTTP et HTTPS)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Configuration de l'API et du Dashboard Traefik
api:
  dashboard: true
  insecure: false

# Comment Traefik découvre les autres services (via Docker)
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Important pour la sécurité !

# Configuration du résolveur de certificats Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: acme.json
      httpChallenge:
        entryPoint: web
